import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Shared/Navber/Navbar";
import Footer from "@/Components/Shared/Footer/Footer";
import { ProvidersTheme } from "@/ThemeProvider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ProvidersTheme>
        <Navbar></Navbar>
          <main className="grow">
            {children}
          </main>
        <Footer></Footer>
        </ProvidersTheme>
      </body>
    </html>
  );
}
